apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: fullstack
type: Opaque
stringData:
  # Change these in production!
  database-url: "postgresql://postgres@CHANGE_ME:CHANGE_ME@pg-cluster.default.svc:5432/fullstack?schema=public"
  redis-url: "redis://redis.default.svc:6379"
  jwt-secret: "CHANGE_ME_TO_SECURE_SECRET"
  arcjet-key: "CHANGE_ME"
